### ISSUE TITLE
Generate Better Documentation

### ISSUE THREAD

**Issue by freexploit** [pimvullers/elementary#139]
The current wiki page(https://wiki.gentoo.org/wiki/Pantheon)  is outdated and not complete. I can help to do this if you can't I just need a way to contact you while writting or if I have any question

**Comment by Maffblaster** [comment]
@pimvullers I also need a way of contacting you. I have a Gentoo machine that's running Pantheon now, however I am experiencing some issues that'd I'd like to talk about. Do you use IRC? How about e-mail?

**Comment by pimvullers** [comment]
You can contact me at elementary@vullersmail.nl. Do note however that I was a PhD student with lots of spare time when I started this overlay. Since 2 years I'm having a full-time job at a company, and I just got a new house. So I'm currently in minimal maintenance mode for this overlay. Still willing to help you out if possible, but it might take a little longer for me to respond.

**Comment by Maffblaster** [comment]
@freexploit Now we both have his email address and you have no excuse to not be upgrading documentation on the Gentoo wiki. :P

@pimvullers I'll be contacting you.

**Comment by Maffblaster** [comment]
I've updated the Gentoo wiki article with what I think is appropriate to get Pantheon working in the repository's current state. I'll continue to keep it maintained as long as I'm involved. You can find it here: https://wiki.gentoo.org/wiki/Pantheon
