### ISSUE TITLE
[sqlheavy] 0.2 Gitorious is down

### ISSUE THREAD

**Issue by simonvanderveldt** [pimvullers/elementary#140]
Hi Pim,

First of all, thanks for the overlay! :)
Just wanted to install Noise, it depends on SQLHeavy 0.2_p20121114 which clones from Gitorious, but Gitorious is down.

I just used [this repo](https://github.com/nemequ/sqlheavy.git) in my local overlay and it worked fine, but that's obviously not an official repo.
Not really sure what else to do, but just wanted to let you know.

(also noticed #113 but it seemed like that wasn't about this issue)

**Comment by Maffblaster** [comment]
Gitorious has [been acquired by GitLab](https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious/) and it's not coming back. Looks like repositories have need made read only. Not much we can do about that...

Looks to me Noise doesn't use SQLHeavy anymore. Only things that _may_ use it are feedler and footnote, both of which may not be actively developed anymore. I think it's safe to close this issue as not fixable since the software that depended upon SQLHeavy either has moved on to better things or isn't developed.

Thanks!
