### ISSUE TITLE
Pantheon-meta build errors

### ISSUE THREAD

**Issue by Renquest00** [pimvullers/elementary#216]
Trying to install Pantheon for the first time.

I run a ~amd64 environment which includes Meson 0.60.2-r1 from the main Gentoo tree. After some research it looks like the new Meson will hard fail if there is ever an unknown option.
 **libecloudproviders** failed with an error that I fixed by removing -Dtest=false line from the emesonargs block:
`meson.build:1:0: ERROR: Unknown options: "test"`
**switchboard** failed to install with a similar error that I solved by removing -Dlibunity=false:
`meson.build:1:0: ERROR: Unknown options: "libunity"`
 **switchboard-plug-mouse-touchpad** with the following error was fixed by removing -Dgnome40=true:
`meson.build:1:0: ERROR: Unknown options: "gnome40"`
**Pantheon-Files** was the last package with this error, fixed by removing -Dwith-unity=disabled :
`meson.build:1:0: ERROR: Unknown options: "with-unity"`

**pantheon-music** failed with the following error:
`No installed vala in || ( dev-lang/vala:0.48 dev-lang/vala:0.46 )`
Commented out VALA_MAX_API_VERSION=0.48 and the package installed. Upon further thought, I'm not sure why portage didn't try to pull in the lower vala version as it is available in the tree still. One of the other package did install a different vala version in a new slot than what I had installed.

**pantheon-tasks** failed with the following error:
`meson.build:28:0: ERROR: Dependency "libecal-2.0" not found, tried pkgconfig and cmake`
I fixed this by manually installing gnome-calendar  (should this have been a dependency?)
this could also be part my fault, the wiki says to change profile to a gnome one but I have KDE Plasma installed and don't want to switch away from it's profile without having tested the replacement (pantheon) Ideally, I would have them both installed for a while.

**wingpanel-indicator-sound** with -bluetooth is failing to find/apply the bluetooth patch. (not sure why this was happening because it looked like good code) I removed the patch section and the package merged without issue.
```
Applying 6.0.1-rm_bluetooth.patch ...
/var/tmp/portage/pantheon-base/wingpanel-indicator-sound-6.0.1/temp/environment: line 1022: /var/tmp/portage/pantheon-base/wingpanel-indicator-sound-6.0.1/files/6.0.1-rm_bluetooth.patch: No such file or directory
/var/tmp/portage/pantheon-base/wingpanel-indicator-sound-6.0.1/temp/environment: line 1025: /var/tmp/portage/pantheon-base/wingpanel-indicator-sound-6.0.1/files/6.0.1-rm_bluetooth.patch: No such file or directory   
```

With those 7 packages 'fixed' the whole meta package installed ( USE="archive cups pulseaudio upower -accessibility -bluetooth -minimal -networkmanager" INPUT_DEVICES="-wacom") My fixes probably aren't the correct way to fix this all and I'm not likely to test pantheon until tonight so I won't know if things are working until then. 

I just thought you might want to have a look at those packages. I would think people using overlays would default to the unstable branch but at the very least you should be ready for when some of the packages causing me problem go to the stable branch. 

Anyway, thank you for making / maintaining this overlay.

**Comment by pimvullers** [comment]
Thanks for reporting. I used to have an ~amd64 system as well. But due to the high frequency of updates I decided to stay on amd64 for my setups now, and only unmask specific packages where I want a newer version. (Also in particular the gnome packages on ~amd64 often caused issues with the elementary ones [since official elementary is using ubuntu with relatively old gnome as basis].)

Also my update policy in general is to just move the files to the latest package version and try a build. If it still works, I commit. There are too many packages to follow specific dependencies etc in detail.

If you find any other points, just report them, and I'll try to address as soon as possible (depends on workload of my job whether I spend free time doing package maintenance or just watching TV/movies to be away from a PC).
