### ISSUE TITLE
Pantheon settings wont open

### ISSUE THREAD

**Issue by ThePelicano** [pimvullers/elementary#231]
I installed pantheon on gentoo, but when I click on the settings icon nothing happens. the settings does not open.

**Comment by pimvullers** [comment]
I just experienced it myself. I have been updating packages by only checking that builds passed, not functionally.

The update to libsoup3 of some of the plugs seems to cause conflicts.
Due to some internet connection issues at my place I will only be able to work on this towards the end of this week.

The solution will be to set the proper dependencies. As a workaround you could revert the checkout of this repo to get an older version of the recently updated packages.

**Comment by pimvullers** [comment]
Various packages have been updated. Please update, and let me know if it is also resolved for you (for me it works currently).
